Bump buildpacks/github-actions from 4.8.0 to 4.8.1 (#95)
* Bump buildpacks/github-actions from 4.8.0 to 4.8.1

Bumps [buildpacks/github-actions](https://github.com/buildpacks/github-actions) from 4.8.0 to 4.8.1.
- [Release notes](https://github.com/buildpacks/github-actions/releases)
- [Commits](https://github.com/buildpacks/github-actions/compare/v4.8.0...v4.8.1)

---
updated-dependencies:
- dependency-name: buildpacks/github-actions
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Fix `clippy::derive_partial_eq_without_eq` lint error

CI was failing due to a new lint added in Rust 1.63:

```
error: you are deriving `PartialEq` and can implement `Eq`
  --> src/procfile.rs:67:17
   |
67 | #[derive(Debug, PartialEq)]
   |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
   |
   = note: `-D clippy::derive-partial-eq-without-eq` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
```

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Ed Morley <501702+edmorley@users.noreply.github.com>