Add integration tests with libcnb-test (#24)
* Add integration tests with libcnb-test


This change adds tests that fully build an app, boot it and assert behavior on it as defined in the procfile build pack.

 
Worth noting that the change requires external dependencies that are only used in integration tests. This causes false positives with clippy, so I've disabled that lint:

```
$ cargo clippy --all-targets --all-features --locked -- --deny warnings
    Checking procfile-buildpack v0.1.0 (/Users/rschneeman/Documents/projects/work/procfile-cnb-rust)
error: external crate `libcnb_test` unused in `procfile_buildpack`: remove the dependency or add `use libcnb_test as _;`
 --> src/main.rs:3:1
  |
3 | #![warn(unused_crate_dependencies)]
  | ^
  |
  = note: `-D unused-crate-dependencies` implied by `-D warnings`
  = help: remove unnecessary dependency `libcnb_test`

error: external crate `ureq` unused in `procfile_buildpack`: remove the dependency or add `use ureq as _;`
 --> src/main.rs:3:1
  |
3 | #![warn(unused_crate_dependencies)]
  | ^
  |
  = help: remove unnecessary dependency `ureq`

error: could not compile `procfile-buildpack` due to 2 previous errors
```

* Update CircleCI config to use machine executor

* Allow unused_crate_dependencies check

Co-authored-by: Manuel Fuchs <manuel.fuchs@salesforce.com>