Fix `clippy::derive_partial_eq_without_eq` lint error
CI was failing due to a new lint added in Rust 1.63:

```
error: you are deriving `PartialEq` and can implement `Eq`
  --> src/procfile.rs:67:17
   |
67 | #[derive(Debug, PartialEq)]
   |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
   |
   = note: `-D clippy::derive-partial-eq-without-eq` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
```